### ISSUE TITLE
Feature Request: Disable Trim Option for Dictionary Entries

### ISSUE THREAD

**Issue by nemeth-it** [Beingpax/VoiceInk#135]
### Feature Request: Disable Trim Option for Dictionary Entries

In transcripts, disconnected phrasing is common:

> Often you can get your bag**. And** check out what you have missed. But always remember, without a clock**. And** a compass, you could lose track of your goals.

A sequence like **`". And"`** breaks sentence flow. You might want to replace it with **`, and`**... buuuuut just **` and`** using the dictionary feature, wouldn't work.

**Problem:**  
Leading/trailing spaces in dictionary terms are **trimmed automatically**, making precise replacements impossible.

---

### ✅ Suggested Fix:

- Remove auto-trim from dictionary inputs, **or**
- Add an option (e.g. checkbox) to control trimming.

This would significantly improve handling of transcript cleanup and nuanced text edits.

**Comment by Beingpax** [comment]
This should be fixed in the latest version 1.36. Can you try it out?

**Comment by nemeth-it** [comment]
It looks good. I replaced `. Und` with ` und`.
- I tried trigger it again, and it worked.
- I retranscribed the same text from history from before the replacement in the dictionary, and it was correctly replaced.

Good work! Thank you!

**Comment by nemeth-it** [comment]
The issue is back.

In the current version, the replacement value is trimmed again, the leading space for example gets removed again. 

![Image](https://github.com/user-attachments/assets/3823c88d-c8f9-498c-9b95-8689c5a666d0)

**Comment by nemeth-it** [comment]
It seems working again with version 1.57. 🎉

I will close this ticket again, thank you!
