### ISSUE TITLE
Add audio or visual cue when model is loaded

### ISSUE THREAD

**Issue by ryanmsnyder** [Beingpax/VoiceInk#76]
When Voice Ink is invoked, it immediately plays a sound. However, this doesn't necessarily mean it's ready to receive audio input. Since there's a brief delay between when Voice Ink starts up and when it's actually ready to receive audio input, the beginning of my dictation often gets cut off. This is a request to add either an audio or visual cue so the user doesn't start speaking too early.

**Comment by Beingpax** [comment]
This is now live. Also the dictation cut off should be resolved. Any updates @ryanmsnyder ?

**Comment by ryanmsnyder** [comment]
Thanks for your response @Beingpax. I installed the most recent update but it I'm still having the issue. If I speak right after I run the shortcut, the first second or two gets cut off but there's no audio or visual cue to know when I can begin speaking. With MacWhisper, for example, there's a visual cue to know when I can start speaking so I don't begin speaking too early.

FWIW, I'm running the Large v3 Turbo (Quantized) model on a M4 Pro Mac Mini.

**Comment by Beingpax** [comment]
The grey button should turn red once the recorder is ready to start. I have made some more improvements to optimize the recorder. This would probably reduce 0.5 sec or more. 

Would love to hear how that works out for you. @ryanmsnyder

**Comment by ryanmsnyder** [comment]
Thanks for the quick response. I just installed the update but unfortunately, I'm still having the same issue. When I launch the recorder, the button is always immediately red (I never see it in a grey state) but it still takes about 1.5-2 seconds to start recording. I tried both the Notch Recorder and the Mini Recorder just in case.

**Comment by Beingpax** [comment]
For audio input, what are you using? Macbook microphone or something else?
